# Generated by Django 5.0.6 on 2024-06-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('articulo', 'Artículo'), ('maceta', 'Maceta'), ('planta', 'Planta')], default='articulo', max_length=20),
        ),
    ]
